# …file has been renamed to PULL_REQUEST_TEMPLATE.md; remove this YAML.
description: Submit a pull request to the CosmosDB project.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Pull Request to the CosmosDB project!
        Please ensure you have read the [Contributing.md](.github/CONTRIBUTING.md) document.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your changes and the motivation for this PR.
      placeholder: What does this PR do? Why is it needed?
    validations:
      required: true
  - type: textarea
    id: issues
    attributes:
      label: Related Issues
      description: List any GitHub issues this PR fixes (e.g., "Fixes #1, Fixes #2").
      placeholder: Fixes #1, Fixes #2
    validations:
      required: false
  - type: textarea
    id: enhancements
    attributes:
      label: Improvements / Enhancements
      description: List any code changes, enhancements, or refactoring included in this PR.
      placeholder: Enhancement 1, Enhancement 2
    validations:
      required: false
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Describe how you tested your changes.
      placeholder: Manual testing, unit tests, etc.
    validations:
      required: false
  - type: input
    id: contributor
    attributes:
      label: Contributor Mention
      description: Mention a project administrator for review (e.g., @githubusername).
      placeholder: '@PlagueHO'
    validations:
      required: false
