name: "🧹 Chore"
description: Request a non-feature, non-bugfix task (e.g., documentation, refactoring, maintenance).
labels: [chore]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for chores such as documentation updates, refactoring, or other maintenance tasks.
  - type: input
    id: module_version
    attributes:
      label: CosmosDB PowerShell Module Version
      description: What version of the CosmosDB PowerShell module are you using? (use `Get-Module -Name CosmosDB`)
      placeholder: e.g. 4.0.0
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Chore Description
      description: Please describe the task or maintenance required.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this task needed?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or details here.
