#
# Module manifest for module 'CosmosDB'
#
# Generated by: Daniel Scott-Raynsford
#
# Generated on: 7/20/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CosmosDB.psm1'

# Version number of this module.
ModuleVersion = '3.5.2.425'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '7d7aeb42-8ed9-4555-b5fd-020795a5aa01'

# Author of this module
Author = 'Daniel Scott-Raynsford'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = '(c) 2019 Daniel Scott-Raynsford. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module provides cmdlets for working with Azure Cosmos DB databases, collections, documents, attachments, offers, users, permissions, triggers, stored procedures and user defined functions.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; GUID = '17a2feff-488b-47f9-8729-e2cec094624c'; ModuleVersion = '1.0.0'; },
               @{ModuleName = 'Az.Resources'; GUID = '48bb344d-4c24-441e-8ea0-589947784700'; ModuleVersion = '1.0.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'types\attachments.types.ps1xml', 'types\collections.types.ps1xml',
               'types\databases.types.ps1xml', 'types\documents.types.ps1xml',
               'types\offers.types.ps1xml', 'types\permissions.types.ps1xml',
               'types\storedprocedures.types.ps1xml',
               'types\triggers.types.ps1xml',
               'types\userdefinedfunctions.types.ps1xml',
               'types\users.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'formats\attachments.formats.ps1xml',
               'formats\collections.formats.ps1xml',
               'formats\databases.formats.ps1xml',
               'formats\documents.formats.ps1xml', 'formats\offers.formats.ps1xml',
               'formats\permissions.formats.ps1xml',
               'formats\storedprocedures.formats.ps1xml',
               'formats\triggers.formats.ps1xml',
               'formats\userdefinedfunctions.formats.ps1xml',
               'formats\users.formats.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-CosmosDbAccount', 'Get-CosmosDbAccountConnectionString',
               'Get-CosmosDbAccountMasterKey', 'Get-CosmosDbAttachment',
               'Get-CosmosDbAttachmentResourcePath', 'Get-CosmosDbCollection',
               'Get-CosmosDbCollectionResourcePath', 'Get-CosmosDbCollectionSize',
               'Get-CosmosDbContextToken',
               'Get-CosmosDBDatabase', 'Get-CosmosDBDatabaseResourcePath',
               'Get-CosmosDBDocument', 'Get-CosmosDBDocumentResourcePath',
               'Get-CosmosDBOffer', 'Get-CosmosDBOfferResourcePath',
               'Get-CosmosDbPermission', 'Get-CosmosDbPermissionResourcePath',
               'Get-CosmosDbStoredProcedure',
               'Get-CosmosDbStoredProcedureResourcePath', 'Get-CosmosDbTrigger',
               'Get-CosmosDbTriggerResourcePath', 'Get-CosmosDbUser',
               'Get-CosmosDbUserResourcePath', 'Get-CosmosDbUserDefinedFunction',
               'Get-CosmosDbUserDefinedFunctionResourcePath',
               'Invoke-CosmosDbStoredProcedure', 'New-CosmosDbAccount',
               'New-CosmosDbAccountMasterKey', 'New-CosmosDbAttachment',
               'New-CosmosDbBackoffPolicy', 'New-CosmosDbCollection',
               'New-CosmosDbCollectionIncludedPathIndex',
               'New-CosmosDbCollectionIncludedPath',
               'New-CosmosDbCollectionExcludedPath',
               'New-CosmosDbCollectionIndexingPolicy',
               'New-CosmosDbCollectionUniqueKey',
               'New-CosmosDbCollectionUniqueKeyPolicy', 'New-CosmosDbDatabase',
               'New-CosmosDbDocument', 'New-CosmosDbContext',
               'New-CosmosDbContextToken', 'New-CosmosDbPermission',
               'New-CosmosDbStoredProcedure', 'New-CosmosDbTrigger',
               'New-CosmosDbUser', 'New-CosmosDbUserDefinedFunction',
               'Remove-CosmosDbAccount', 'Remove-CosmosDbAttachment',
               'Remove-CosmosDbCollection', 'Remove-CosmosDbDatabase',
               'Remove-CosmosDbDocument', 'Remove-CosmosDbPermission',
               'Remove-CosmosDbStoredProcedure', 'Remove-CosmosDbTrigger',
               'Remove-CosmosDbUser', 'Remove-CosmosDbUserDefinedFunction',
               'Set-CosmosDbAccount', 'Set-CosmosDbAttachment',
               'Set-CosmosDbCollection', 'Set-CosmosDbDocument', 'Set-CosmosDbOffer',
               'Set-CosmosDbStoredProcedure', 'Set-CosmosDbTrigger',
               'Set-CosmosDbUser', 'Set-CosmosDbUserDefinedFunction'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'New-CosmosDbConnection'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'CosmosDB', 'DocumentDb', 'Azure', 'PSEdition_Core', 'PSEdition_Desktop',
               'Windows', 'Linux', 'MacOS'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PlagueHO/CosmosDB/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PlagueHO/CosmosDB'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
  ## What is New in CosmosDB Unreleased

  - Update `BuildHelpers` to version 2.0.11.
  - Update `Psake` to version 4.9.0.
  - Update `Pester` to version 4.10.1.
  - Update `PSScriptAnalyzer` to version 1.18.3.
  - Change Azure Pipeline Linux build to test PowerShell Core 6.2.3-1.
  - Change TravisCI Linux build to test PowerShell Core 6.2.3-1.
  - Change TravisCI MacOS build to test PowerShell Core 6.2.3-1.
  - Add PowerShell 7 test to Azure Pipeline - fixes [Issue #325](https://github.com/PlagueHO/CosmosDB/issues/325).
  - Fix bug converting Secure String in PowerShell 7 on Linux - fixes [Issue #323](https://github.com/PlagueHO/CosmosDB/issues/323).
  - Fix issue in Azure Pipeline in MacOS build job - fixes [Issue #326](https://github.com/PlagueHO/CosmosDB/issues/326).
  - Remove TravisCI Pipeline - fixes [Issue #327](https://github.com/PlagueHO/CosmosDB/issues/327).

  ## What is New in CosmosDB 3.5.1.458

  November 12, 2019

  - Change `psakefile.ps1` to detect Azure Pipelines correctly.
  - Updated `BuildHelpers` support module for CI pipelines to 2.0.10.
  - Added PowerShell Gallery badge to `README.md`.
  - Refactored `Invoke-CosmosDbRequest` and added
    `Get-CosmosDbAuthorizationHeadersFromContext` to split out function to pull
    token out of `Context` object. This was done to reduce the size of the
    `Invoke-CosmosDbRequest` function and to improve testability.
  - Fix TravisCI MacOS build - fixes [Issue #313](https://github.com/PlagueHO/CosmosDB/issues/313).
  - Created helper function `Format-CosmosDbDocumentPartitionKey` to
    format the partition key string passed to `x-ms-documentdb-partitionkey`
    in document functions.
  - Add support for integer partition keys to functions
    `Get-CosmosDbDocument`, `New-CosmosDbDocument`, `Remove-CosmosDbDocument`
    and `Set-CosmosDbDocument`.

  ## What is New in CosmosDB 3.5.0.425

  July 19, 2019

  - Fix issue with integration test execution error in Azure DevOps
    when running against a pull request and the contributor has not
    set build environment variables for connecting to Azure - fixes [Issue #304](https://github.com/PlagueHO/CosmosDB/issues/304).
  - Added `.markdownlint.json` to enable linting of markdown files.
  - Added optional `ETag` parameter to `Set-CosmosDbDocument` to check if
    the document has been updated since last get.

  ## What is New in CosmosDB 3.4.0.410

  June 29, 2019

  - Added `OfferThroughput` parameter to `New-CosmosDbDatabase`
    function - fixes [Issue #110](https://github.com/PlagueHO/CosmosDB/issues/110).

  ## What is New in CosmosDB 3.3.0.404

  June 22, 2019

  - Moved CosmosDB namespace class definitions into C# project to be built
    into a .NET Standard 2.0 DLL that can be loaded instead of a CS file.
    This is to work around a problem with Azure Functions 2.0 where
    types can not be compiled in the runtime (see [this issue](https://github.com/Azure/azure-functions-powershell-worker/issues/220)) -
    fixes [Issue #290](https://github.com/PlagueHO/CosmosDB/issues/290).

  ## What is New in CosmosDB 3.2.4.375

  May 30, 2019

  - Update `requirements.psd1` to install modules `Az.Resources` 1.3.1 and
    `Az.Accounts` 1.5.1.
  - Change `requirements.psd1` to specify `minimumversion` of `Az.Resources`
    and `Az.Accounts`.
  - Enabled tests and removed the warning when executing the function
    `Get-CosmosDbAccountConnectionString` because the underlying REST API
    has been fixed and now functions correctly - fixes [Issue #291](https://github.com/PlagueHO/CosmosDB/issues/291).
  - Added parameter `MasterKeyType` to function `Get-CosmosDbAccountConnectionString`
    to only return a specific connection string - fixes [Issue #291](https://github.com/PlagueHO/CosmosDB/issues/291).

  ## What is New in CosmosDB 3.2.3.358

  April 5, 2019

  - Fix incorrectly encoded strings being returned by `Get-CosmosDbDocument`
    when UTF-8 results are returned - fixes [Issues #282](https://github.com/PlagueHO/CosmosDB/issues/282).
  - Rename `CosmosDb.psdepend.ps1` to `requirements.psd1` to be a more
    generic name.

  ## What is New in CosmosDB 3.2.2.348

  March 19, 2019

  - Added Azure Pipelines YAML definition for executing automated
    testing on a daily schedule - fixes [Issue #272](https://github.com/PlagueHO/CosmosDB/issues/272).
  - Extend AppVeyor test automation to run on Windows Server 2012R2
    and Windows Server 2016.
  - Update `cosmosdb.psdepend.psd1` to install modules `Az.Resources` 1.2.0 and
    `Az.Accounts` 1.4.0.
  - Added `Windows`, `Linux` and `MacOS` tags to module manifest to
    improve searchability in PowerShell Gallery.

  ## What is New in CosmosDB 3.2.1.331

  February 22, 2019

  - Added support for `PartitionKey` in `*-CosmosDBAttachment`
    functions - fixes [Issue #274](https://github.com/PlagueHO/CosmosDB/issues/274).
  - Update `cosmosdb.psdepend.psd1` to install modules `Az.Resources` 1.1.2 and
    `Az.Accounts` 1.3.0.
  - Suppress verbose output when loading module during automated
    testing to reduce output.

  ## What is New in CosmosDB 3.2.0.320

  February 6, 2019

  - Convert module name to be a variable in PSake file to make it more
    easily portable between projects.
  - Fix `Notes` display in Readme Markdown - fixes [Issue #269](https://github.com/PlagueHO/CosmosDB/issues/269).
  - Update `cosmosdb.psdepend.psd1` to install modules `Az` 1.2.1 and
    `Pester` 4.7.0.
  - Deprecate `Hash` index policy kind and throw exception when used
    in `New-CosmosDbCollectionIncludedPathIndex`. See [this page](https://docs.microsoft.com/en-us/azure/cosmos-db/index-types#index-kind)
    for more information - fixes [Issue #271](https://github.com/PlagueHO/CosmosDB/issues/271).

  ## What is New in CosmosDB 3.1.0.293

  December 26, 2018

  - Updated manifest to include required modules `Az.Accounts` 1.0.0
    and `Az.Resources` 1.0.0.
  - Updated manifest to include `CompatiblePSEditions` of ''Desktop'' and
    ''Core''.
  - Updated minimum supported PowerShell version to 5.1.
  - Updated `cosmosdb.depend.psd1` to ensure `Az` modules are installed
    when running ''Deploy'' PSake task.
  - Improve build task code to ensure Git tag is correctly set.
  '

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

